### ISSUE TITLE
UIDevice.simulator? doesn't return true when running in simulator

### ISSUE THREAD

**Issue by abaroody** [rubymotion-community/BubbleWrap#473]
As far as I can tell UIDevice.simulator? no longer returns true when running in the simulator. The method uses UIDevice.currentDevice.model which now returns only "iPhone" for me instead of "iPhone Simulator." Does anyone else have this issue?

**Comment by markrickert** [comment]
Here's how we solved it in RMQ - https://github.com/infinitered/rmq/pull/296/files

I'd welcome a pull request with this fix in it.

**Comment by holgersindbaek** [comment]
I just installed the latest build. Now "Device.simulator?" returns true when running in simulator, but it also returns true when running on device!

**Comment by holgersindbaek** [comment]
This pull request should fix it:

https://github.com/rubymotion/BubbleWrap/pull/475
