### ISSUE TITLE
iOS 11 image picker controller crash

### ISSUE THREAD

**Issue by apriltg** [rubymotion-community/BubbleWrap#492]
no issue for camera.
only crash when choosing photo from photo library.

bubble-wrap (1.9.6)
rubymotion 5.0
ruby-2.2.1
xcode 8.3.3

`BW::Device.camera.any.picture({media_types: [:image]}, controller, &block)`

ERROR:
can't modify frozen/immutable hash (RuntimeError)
camera.rb line 188
rb_scope__imagePickerController:didFinishPickingMediaWithInfo:__block__

**Comment by apriltg** [comment]
I have created a PR. Just deleting one line of code.

https://github.com/rubymotion/BubbleWrap/pull/493

**Comment by andrewhavens** [comment]
This has been merged and will be included in the next release
