### ISSUE TITLE
Issue with Bubblewrap on 10.13.4

### ISSUE THREAD

**Issue by tsugua** [rubymotion-community/BubbleWrap#497]
WARNING! Possible cyclical dependency between /Users/user/.rvm/gems/ruby-2.4.1/gems/bubble-wrap-1.9.6/motion/util/deprecated.rb and /Users/user/.rvm/gems/ruby-2.4.1/gems/bubble-wrap-1.9.6/motion/shortcut.rb's class hierarchy. Consider revision if runtime exceptions occur around undefined symbols.
  WARNING! Possible cyclical dependency between /Users/user/.rvm/gems/ruby-2.4.1/gems/bubble-wrap-1.9.6/lib/bubble-wrap/version.rb and /Users/user/.rvm/gems/ruby-2.4.1/gems/bubble-wrap-1.9.6/motion/shortcut.rb's class hierarchy. Consider revision if runtime exceptions occur around undefined symbols.

**Comment by andrewhavens** [comment]
These are warnings and not errors. These can be ignored.
